export const ADD_CUSTOMER_BAG = 'ADD_CUSTOMER_BAG';
export const REMOVE_CUSTOMER_BAG = 'REMOVE_CUSTOMER_BAG';
export const UPDATE_CUSTOMER_BAGS = 'UPDATE_CUSTOMER_BAGS';
export const SET_CUSTOMER_BAGS = 'SET_CUSTOMER_BAGS';
export const SET_CUSTOMER_BAGS_STORED = 'SET_CUSTOMER_BAGS_STORED';